# https://www.dartlang.org/guides/language/analysis-options

include: package:pedantic/analysis_options.yaml

analyzer:
  strong-mode:
    implicit-casts: false
  exclude:
    - example/**/*.dart
    - test/**/*.dart
linter:
  rules:
    - public_member_api_docs
    - type_annotate_public_apis
    - void_checks
    - unnecessary_new
