targets:
  $default:
    builders:
      artemis:
        options:
          schema_mapping:
            - schema: lib/graphbrainz.schema.json
              queries_glob: lib/queries/ed_sheeran.query.graphql
              output: lib/queries/ed_sheeran.query.dart
              resolve_type_field: __typename
          custom_parser_import: 'package:graphbrainz_example/coercers.dart'
          scalar_mapping:
          - graphql_type: Date
            dart_type: DateTime
            use_custom_parser: true
          - graphql_type: Time
            dart_type: DateTime
            use_custom_parser: true
          - graphql_type: DiscID
            dart_type: String
          - graphql_type: MBID
            dart_type: String
          - graphql_type: ASIN
            dart_type: String
          - graphql_type: IPI
            dart_type: String
          - graphql_type: ISNI
            dart_type: String
          - graphql_type: ISRC
            dart_type: String
          - graphql_type: URLString
            dart_type: String
          - graphql_type: Degrees
            dart_type: double
          - graphql_type: Locale
            dart_type: String
